Added custom FPL support
ivao-xa/TrainingServer pull request #5
Opened 2022-08-20 20:13 UTC by NikoDervaric

Scenario Loader now supports spawning aircraft with predefined flightplans.

2022-08-20 21:25 UTC, wessupermare requested changes
Good stuff generally speaking. Just a couple style & input safety things to check into then you should be all good.

2022-08-20 21:25 UTC, wessupermare commented on Plugins/ScenarioLoader/Plugin.cs
> +            executingTask = Task.Run(async () => await ExecuteFileAsync(server, path));
```suggestion
            executingTask = ExecuteFileAsync(server, path);
```

This'll help with exception propagation.

2022-08-20 21:25 UTC, wessupermare commented on Plugins/ScenarioLoader/Plugin.cs
> +                            }
```suggestion
                            foreach (string str in split_flight)
                                Console.WriteLine(str + '\n');
```
For style consistency, either remove the braces or put the opening brace on its own line.

2022-08-20 21:25 UTC, wessupermare commented on Plugins/ScenarioLoader/Plugin.cs
> +                                                        new(char.Parse(flightdata[0]), char.Parse(flightdata[1]), flightdata[2], flightdata[3], flightdata[4], new(), new(), flightdata[7], flightdata[
```suggestion
                                                        new(flightdata[0].Single(), flightdata[1].Single(), flightdata[2], flightdata[3], flightdata[4], new(), new(), flightdata[7], flightdata[8], 0, 0, 0, 0, "NONE", remarks, route),
```

`char.Parse` isn't safe. Consider either `.Single()` if you're confident in the data or either `[0]` or `char.TryParse()` if you're less sure.

2022-08-20 21:39 UTC, NikoDervaric commented on Plugins/ScenarioLoader/Plugin.cs
> +            executingTask = Task.Run(async () => await ExecuteFileAsync(server, path));
Change accepted for better exception propagation.

2022-08-20 21:39 UTC, NikoDervaric commented on Plugins/ScenarioLoader/Plugin.cs
> +                            }
Removed braces for consistency.

2022-08-20 21:40 UTC, NikoDervaric commented on Plugins/ScenarioLoader/Plugin.cs
> +                                                        new(char.Parse(flightdata[0]), char.Parse(flightdata[1]), flightdata[2], flightdata[3], flightdata[4], new(), new(), flightdata[7], flightdata[
Switched to `Single()`

2022-08-20 21:41 UTC, NikoDervaric commented
All changes applied as per suggestions.

2022-08-20 21:51 UTC, wessupermare requested changes
Almost there. As discussed over Discord, just putting this here as a reminder. :)

2022-08-20 21:51 UTC, wessupermare commented on Plugins/ScenarioLoader/Plugin.cs
> +                                                        new(flightdata[0].Single(), flightdata[1].Single(), flightdata[2], flightdata[3], flightdata[4], new(), new(), flightdata[7], flightdata[8], 0,
These calls to `Single()` need a check before they are safe. Consider adding a check to ensure that `flightdata[0].Length == 1 && flightdata[1].Length == 1` before line 80.

2022-08-23 22:15 UTC, wessupermare approved these changes

2022-08-23 22:15 UTC, merged